substitutions:
  main_name: "ESPHome Hello World"

esphome:
  name: "esphomehelloworld"
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

api:
logger:
ota:

web_server:
  port: 80

switch:
  - platform: gpio
    name: ${main_name} Pin D4
    pin: D4
    inverted: True

binary_sensor:
  - platform: status
    name: ${main_name} Status

sensor:
  - platform: wifi_signal
    name: ${main_name} WiFi Signal
    update_interval: 60s

  - platform: uptime
    name: ${main_name} Uptime

text_sensor:
  - platform: version
    name: ${main_name} Version
