# https://www.home-assistant.io/integrations/binary_sensor.mqtt/

platform: mqtt
name: Application Restricted Zone Notifier Python
state_topic: "Restricted_zone_python"
value_template: '{{ value_json.Alert }}'
payload_on: True
payload_off: False
device_class: motion
force_update: true
